# Generated by Django 5.0.7 on 2024-10-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'managed': False},
        ),
    ]
