# Generated by Django 5.0.7 on 2024-10-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Data', '0002_alter_resource_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='TEMPERATURE_TABLE',
        ),
    ]
