# Generated by Django 5.0.7 on 2024-10-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Data', '0005_alter_resource_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='SAMPLE_DATA',
        ),
    ]
