# Generated by Django 5.0.7 on 2024-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sql_Data', '0002_device_allocated_device_name_device_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='working',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='allocated',
            field=models.CharField(max_length=50),
        ),
    ]
