# Generated by Django 5.0.7 on 2024-10-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detailed_Graph', '0002_alter_temperaturedata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temperaturedata',
            table='TEMPERATURE_DATA_TABLE',
        ),
    ]
