# Generated by Django 5.0.7 on 2024-10-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detailed_Graph', '0003_alter_temperaturedata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temperaturedata',
            table='SAMPLE_DATA',
        ),
    ]
