# Generated by Django 5.0.7 on 2024-10-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='AUTH_LOGIN_TABLE',
        ),
    ]
