# Generated by Django 5.0.7 on 2024-10-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='AUTHENTICATION',
        ),
    ]
